version: '3.8'
services:
  devcontainer:
    build:
        context: .
        dockerfile: Dockerfile
#    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
      - dotjulia:/home/vscode/.julia
    command: sleep infinity

volumes:
  dotjulia:
    external: true 
    name: dotjulia
